version: '2'
services:
  mongo:
    image: mongo:3.4
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test 
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/My-Site
     - /My-Site/node_modules
     